version: '3.7'
services:
    postgres:
        image: postgres
        restart: always
        environment:
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres

        ports:
            - "5432:5432"

        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
